#### NVIDIA setting. Remove when using Intel.
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# Disable access control for the current user.
xhost +SI:localuser:$USER

# Set themes, etc.
# gnome-settings-daemon &

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Set default cursor.
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate.
xset r rate 200 25

# hidpi
xrandr --dpi 192

# always keep numlock on
# numlockx &

# Finally start Emacs
exec emacs
