#### NVIDIA setting. Remove when using Intel.
# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

# Disable access control for the current user.
xhost +SI:localuser:$USER

# Set themes, etc.
xrdb ~/.Xresources

# Stop creating lots of serverauth files
xserverauthfile=$XAUTHORITY

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Set keyboard repeat rate.
xset r rate 200 25

# hidpi
xrandr --dpi 192

# always keep numlock on
# numlockx &

# Finally start Emacs
exec emacs
